const countries = {
    Afghanistan: false,
    'Åland Islands': false,
    Albania: false,
    Algeria: false,
    'American Samoa': false,
    Andorra: false,
    Angola: false,
    Anguilla: false,
    Antarctica: false,
    'Antigua and Barbuda': false,
    Argentina: false,
    Armenia: false,
    Aruba: false,
    Australia: false,
    Austria: false,
    Azerbaijan: false,
    Bahamas: false,
    Bahrain: false,
    Bangladesh: false,
    Barbados: false,
    Belarus: false,
    Belgium: false,
    Belize: false,
    Benin: false,
    Bermuda: false,
    Bhutan: false,
    Bolivia: false,
    'Bonaire, Sint Eustatius and Saba': false,
    'Bosnia and Herzegovina': false,
    Botswana: false,
    'Bouvet Island': false,
    Brazil: false,
    'British Indian Ocean Territory': false,
    'British Virgin Islands': false,
    'Brunei Darussalam': false,
    Bulgaria: false,
    'Burkina Faso': false,
    Burma: false,
    Burundi: false,
    Cambodia: false,
    Cameroon: false,
    Canada: false,
    'Cape Verde': false,
    'Cayman Islands': false,
    'Central African Republic': false,
    Chad: false,
    Chile: false,
    China: false,
    'Christmas Island': false,
    'Cocos (Keeling) Islands': false,
    Colombia: false,
    Comoros: false,
    Congo: false,
    'Cook Islands': false,
    'Costa Rica': false,
    "Côte d'Ivoire": false,
    Croatia: false,
    Cuba: false,
    Cyprus: false,
    'Czech Republic': false,
    Czechoslovakia: false,
    'Democratic Republic of the Congo': false,
    Denmark: false,
    Djibouti: false,
    Dominica: false,
    'Dominican Republic': false,
    'East Germany': false,
    Ecuador: false,
    Egypt: false,
    'El Salvador': false,
    'Equatorial Guinea': false,
    Eritrea: false,
    Estonia: false,
    Ethiopia: false,
    'Falkland Islands': false,
    'Faroe Islands': false,
    'Federal Republic of Yugoslavia': false,
    'Federated States of Micronesia': false,
    Fiji: false,
    Finland: false,
    France: false,
    'French Guiana': false,
    'French Polynesia': false,
    'French Southern Territories': false,
    Gabon: false,
    Gambia: false,
    Georgia: false,
    Germany: false,
    Ghana: false,
    Gibraltar: false,
    Greece: false,
    Greenland: false,
    Grenada: false,
    Guadeloupe: false,
    Guam: false,
    Guatemala: false,
    Guernsey: false,
    Guinea: false,
    'Guinea-Bissau': false,
    Guyana: false,
    Haiti: false,
    'Heard Island and McDonald Islands': false,
    'Holy See (Vatican City State)': false,
    Honduras: false,
    'Hong Kong': false,
    Hungary: false,
    Iceland: false,
    India: false,
    Indonesia: false,
    Iran: false,
    Iraq: false,
    Ireland: false,
    'Isle of Man': false,
    Israel: false,
    Italy: false,
    Jamaica: false,
    Japan: false,
    Jersey: false,
    Jordan: false,
    Kazakhstan: false,
    Kenya: false,
    Kiribati: false,
    Korea: false,
    Kosovo: false,
    Kuwait: false,
    Kyrgyzstan: false,
    Laos: false,
    Latvia: false,
    Lebanon: false,
    Lesotho: false,
    Liberia: false,
    Libya: false,
    Liechtenstein: false,
    Lithuania: false,
    Luxembourg: false,
    Macao: false,
    Madagascar: false,
    Malawi: false,
    Malaysia: false,
    Maldives: false,
    Mali: false,
    Malta: false,
    'Marshall Islands': false,
    Martinique: false,
    Mauritania: false,
    Mauritius: false,
    Mayotte: false,
    Mexico: false,
    Moldova: false,
    Monaco: false,
    Mongolia: false,
    Montenegro: false,
    Montserrat: false,
    Morocco: false,
    Mozambique: false,
    Myanmar: false,
    Namibia: false,
    Nauru: false,
    Nepal: false,
    Netherlands: false,
    'Netherlands Antilles': false,
    'New Caledonia': false,
    'New Zealand': false,
    Nicaragua: false,
    Niger: false,
    Nigeria: false,
    Niue: false,
    'Norfolk Island': false,
    'North Korea': false,
    'North Vietnam': false,
    'Northern Mariana Islands': false,
    Norway: false,
    Oman: false,
    Pakistan: false,
    Palau: false,
    Palestine: false,
    'Palestinian Territory': false,
    Panama: false,
    'Papua New Guinea': false,
    Paraguay: false,
    Peru: false,
    Philippines: false,
    Poland: false,
    Portugal: false,
    Pitcairn: false,
    'Puerto Rico': false,
    Qatar: false,
    'Republic of Macedonia': false,
    'Réunion': false,
    Romania: false,
    Russia: false,
    Rwanda: false,
    'Saint Barthélemy': false,
    'Saint Helena': false,
    'Saint Kitts and Nevis': false,
    'Saint Lucia': false,
    'Saint Martin (French part)': false,
    'Saint Pierre and Miquelon': false,
    'Saint Vincent and the Grenadines': false,
    Samoa: false,
    'San Marino': false,
    'Sao Tome and Principe': false,
    'Saudi Arabia': false,
    Senegal: false,
    Serbia: false,
    'Serbia and Montenegro': false,
    Seychelles: false,
    Siam: false,
    'Sierra Leone': false,
    Singapore: false,
    Slovakia: false,
    Slovenia: false,
    'Solomon Islands': false,
    Somalia: false,
    'South Africa': false,
    'South Georgia and the South Sandwich Islands': false,
    'South Korea': false,
    'Soviet Union': false,
    Spain: false,
    'Sri Lanka': false,
    Sudan: false,
    Suriname: false,
    'Svalbard and Jan Mayen': false,
    Swaziland: false,
    Sweden: false,
    Switzerland: false,
    Syria: false,
    Taiwan: false,
    Tajikistan: false,
    Tanzania: false,
    Thailand: false,
    'Timor-Leste': false,
    Togo: false,
    Tokelau: false,
    Tonga: false,
    'Trinidad and Tobago': false,
    Tunisia: false,
    Turkey: false,
    Turkmenistan: false,
    'Turks and Caicos Islands': false,
    Tuvalu: false,
    'U.S. Virgin Islands': false,
    Uganda: false,
    Ukraine: false,
    'United Arab Emirates': false,
    'United Kingdom': false,
    'United States': false,
    'United States Minor Outlying Islands': false,
    Uruguay: false,
    Uzbekistan: false,
    Vanuatu: false,
    Venezuela: false,
    Vietnam: false,
    'Wallis and Futuna': false,
    'West Germany': false,
    'Western Sahara': false,
    Yemen: false,
    Yugoslavia: false,
    Zaire: false,
    Zambia: false,
    Zimbabwe: false
}

export default countries //what, you expected me to fetch the list every time?